### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by LeahB8** [learn-co-curriculum/js-rails-as-api-using-fast-json-api#2]
![Screen Shot 2019-05-18 at 18 39 16](https://user-images.githubusercontent.com/47163554/57973163-5b971d80-799c-11e9-973c-07ed0d4d5497.png)

Hello,
Just a heads up that the @sightings within the SightingSerailizer.new() produces data :null when loading the api on localhost:3000/sightings/2. It should be @sighting instead of @sightings. It was written in the above code snippet too. 
Many thanks,
Leah Boyd

**Comment by maxwellbenton** [comment]
HI @LeahB8,

Thank you for spotting this and providing feedback! We've updated this lesson's content, fixed
this typo and believe this issue has been resolved.

Thank you for contributing to a learn.co lesson!
