### ISSUE TITLE
bundle locked to mimemagic 0.3.3

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/js-rails-as-api-using-fast-json-api#22]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://github.com/learn-co-curriculum/js-rails-as-api-using-fast-json-api

## What should be changed?

Been getting the following error on the last 4-5 labs or so.
Didn't know if it was an issue on my computer of what the labs are requiring is outdated. 

Your bundle is locked to mimemagic (0.3.3) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of mimemagic (0.3.3) has removed
it. You'll need to update your bundle to a version other than mimemagic (0.3.3)
that hasn't been removed in order to install.

## Additional context

> Add any other context about the problem here.

**Comment by ihollander** [comment]
Fixed by #23
